---
- name : playbook
  hosts: "{{ target }}"
  
  tasks: 
    - name: configurer une description
      ios_command:
        commands:
           - show running-config
      register: cli_result

    - name: print output 
      debug:
        msg: "{{ cli_result }}"
       
    - name: task3
      file:
        path:  "outputs"
        state: directory
      run_once: true
     
    - name: ecrire le fichier
      copy:
        content: "{{ cli_result.stdout[0]}}\n"
        dest: "outputs/{{ inventory_hostname ]].txt"
